# Generated by Django 4.2.5 on 2023-09-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='programs',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='reg',
            new_name='regdate',
        ),
    ]
