# Generated by Django 4.2.5 on 2023-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_rename_programs_student_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry',
            new_name='enquirytext',
        ),
    ]
