# Generated by Django 4.2.5 on 2023-09-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooStore',
            new_name='BookStore',
        ),
    ]
